INSERT INTO blog_articulo (titulo, contenido, fecha_creacion, fecha_actualizacion, imagen_portada, autor_id) VALUES
('La evolución de los gráficos en videojuegos', 'Desde los píxeles de 8 bits hasta el ray tracing actual, los gráficos han sido clave en la experiencia gamer.', NOW(), NOW(), NULL, 1),
('Top 5 RPGs de la última década', 'Los juegos de rol han marcado tendencia con historias profundas y mundos abiertos. Descubre los mejores.', NOW(), NOW(), NULL, 1),
('¿Por qué Minecraft sigue siendo popular?', 'La creatividad y la comunidad mantienen a Minecraft como uno de los títulos más jugados del mundo.', NOW(), NOW(), NULL, 1),
('El impacto de los eSports en la cultura gamer', 'Los deportes electrónicos han transformado el gaming en un fenómeno global con millones de seguidores.', NOW(), NOW(), NULL, 1),
('Nintendo Switch: innovación portátil', 'La consola híbrida de Nintendo revolucionó la forma de jugar en casa y en movimiento.', NOW(), NOW(), NULL, 1),
('La historia de The Legend of Zelda', 'Una saga que ha marcado generaciones con aventuras épicas y mundos mágicos.', NOW(), NOW(), NULL, 1),
('Los mejores juegos indie de 2025', 'Los desarrolladores independientes sorprenden con propuestas originales y jugabilidad única.', NOW(), NOW(), NULL, 1),
('¿Qué esperar de GTA VI?', 'Rumores, filtraciones y expectativas sobre el próximo gran lanzamiento de Rockstar Games.', NOW(), NOW(), NULL, 1),
('La importancia de la narrativa en los videojuegos', 'Historias envolventes y personajes memorables hacen que los juegos sean más que solo entretenimiento.', NOW(), NOW(), NULL, 1),
('El regreso de los juegos retro', 'La nostalgia impulsa remakes y colecciones de clásicos para nuevas generaciones.', NOW(), NOW(), NULL, 1),
('PlayStation vs Xbox: la batalla continúa', 'Comparativa de consolas, exclusivos y servicios en la guerra por el mercado gamer.', NOW(), NOW(), NULL, 1),
('Cómo elegir tu primer PC gamer', 'Consejos sobre hardware, periféricos y presupuesto para iniciarte en el gaming de PC.', NOW(), NOW(), NULL, 1),
('La revolución de la realidad virtual', 'VR promete experiencias inmersivas y nuevas formas de jugar.', NOW(), NOW(), NULL, 1),
('Fortnite: más que un battle royale', 'Eventos, colaboraciones y una comunidad activa mantienen a Fortnite en la cima.', NOW(), NOW(), NULL, 1),
('El fenómeno de Among Us', 'Un juego simple que conquistó a millones con su mecánica de deducción social.', NOW(), NOW(), NULL, 1),
('Los mejores juegos cooperativos para jugar con amigos', 'Opciones ideales para divertirse en grupo y fortalecer lazos.', NOW(), NOW(), NULL, 1),
('La música en los videojuegos', 'Bandas sonoras que han quedado en la memoria de los jugadores.', NOW(), NOW(), NULL, 1),
('Cyberpunk 2077: de la polémica al éxito', 'El camino de CD Projekt Red tras un lanzamiento complicado y su redención.', NOW(), NOW(), NULL, 1),
('El rol de las mujeres en la industria gamer', 'Desarrolladoras, jugadoras y personajes femeninos que inspiran.', NOW(), NOW(), NULL, 1),
('Cómo los videojuegos ayudan al aprendizaje', 'Gamificación y títulos educativos que potencian habilidades.', NOW(), NOW(), NULL, 1),
('La evolución de los controles de juego', 'Desde joysticks clásicos hasta mandos adaptativos y VR.', NOW(), NOW(), NULL, 1),
('Pokémon: más de 25 años atrapando criaturas', 'La franquicia sigue creciendo con nuevos juegos y generaciones.', NOW(), NOW(), NULL, 1),
('El auge de los juegos móviles', 'Smartphones y tablets han democratizado el acceso al gaming.', NOW(), NOW(), NULL, 1),
('Los mejores juegos de terror para valientes', 'Títulos que desafían tus nervios y te sumergen en atmósferas inquietantes.', NOW(), NOW(), NULL, 1),
('La comunidad modder y su impacto', 'Mods que mejoran, transforman y extienden la vida útil de los juegos.', NOW(), NOW(), NULL, 1),
('El futuro del cloud gaming', 'Jugar sin consola ni PC potente gracias a la nube.', NOW(), NOW(), NULL, 1),
('Animal Crossing: el refugio virtual', 'Un juego que ofrece paz, creatividad y comunidad en tiempos difíciles.', NOW(), NOW(), NULL, 1),
('La importancia de la accesibilidad en videojuegos', 'Opciones y tecnologías para que todos puedan jugar.', NOW(), NOW(), NULL, 1),
('Los mejores juegos de carreras de 2025', 'Simulación, arcade y adrenalina en los títulos más destacados del género.', NOW(), NOW(), NULL, 1),
('Cómo los videojuegos inspiran otras artes', 'Cine, música y literatura influenciados por el mundo gamer.', NOW(), NOW(), NULL, 1);